export default {
  'poppins-regular': require('../assets/fonts/Poppins-Regular.ttf'),
  'poppins-bold': require('../assets/fonts/Poppins-Bold.ttf'),
  'poppins-semiBold': require('../assets/fonts/Poppins-SemiBold.ttf'),
  'Inter-Black': require('../assets/fonts/Inter-Black.ttf'),
  'Inter-Bold': require('../assets/fonts/Inter-Bold.ttf'),
  'Inter-ExtraBold': require('../assets/fonts/Inter-ExtraBold.ttf'),
  'Inter-ExtraLight': require('../assets/fonts/Inter-ExtraLight.ttf'),
  'Inter-Light': require('../assets/fonts/Inter-Light.ttf'),
  'Inter-Medium': require('../assets/fonts/Inter-Medium.ttf'),
  'Inter-Regular': require('../assets/fonts/Inter-Regular.ttf'),
  'Inter-SemiBold': require('../assets/fonts/Inter-SemiBold.ttf'),
  'Inter-Thin': require('../assets/fonts/Inter-Thin.ttf'),
  'Roboto-Black': require('../assets/fonts/Roboto-Black.ttf'),
  'Roboto-BlackItalic': require('../assets/fonts/Roboto-BlackItalic.ttf'),
  'Roboto-Bold': require('../assets/fonts/Roboto-Bold.ttf'),
  'Roboto-BoldItalic': require('../assets/fonts/Roboto-BoldItalic.ttf'),
  'Roboto-Italic': require('../assets/fonts/Roboto-Italic.ttf'),
  'Roboto-Light': require('../assets/fonts/Roboto-Light.ttf'),
  'Roboto-LightItalic': require('../assets/fonts/Roboto-LightItalic.ttf'),
  'Roboto-Medium': require('../assets/fonts/Roboto-Medium.ttf'),
  'Roboto-MediumItalic': require('../assets/fonts/Roboto-MediumItalic.ttf'),
  'Roboto-Regular': require('../assets/fonts/Roboto-Regular.ttf'),
  'Roboto-Thin': require('../assets/fonts/Roboto-Thin.ttf'),
  'Roboto-ThinItalic': require('../assets/fonts/Roboto-ThinItalic.ttf'),
};
